### PR TITLE
support tabel-mode

### PR DESCRIPTION
**Pull request by xxbld**
support tabel-mode
allow scopedSlots.default as item-mode compontent render;
item  type: set [Function, Object],

### CODE REVIEW

**Comment by tangbc** [comment]
Something wrong with `npm run test`:

```bash
=============================== Coverage summary ===============================
Statements   : 68.61% ( 153/223 )
Branches     : 55.44% ( 107/193 )
Functions    : 78.13% ( 25/32 )
Lines        : 68.33% ( 151/221 )
================================================================================
Test Suites: 10 failed, 4 passed, 14 total
Tests:       18 failed, 11 passed, 29 total
Snapshots:   0 total
Time:        5.524s
```

**Comment by xxbld** [comment]
en...it`s something  wrong  in vue test
bowser  this.$scopedSlots.default=undefined
jest this.$scopedSlots.default=function

image

**Comment by xxbld** [comment]
https://github.com/vuejs/vue-test-utils/issues/1327

**Comment by tangbc** [comment]
Some conflicts to `master`.

**Comment by tangbc** [comment]
Still have conflicts now?

**Comment by xxbld** [comment]
> Still have conflicts now?
no conflicts ,  least changes.
but vue test bug still

**Comment by xxbld** [comment]
@tangbc 
can you review this pr?

changed $scopedSlots.default to $scopedSlots.item
and jest passed

https://vuejs.org/v2/api/#vm-scopedSlots
> All $slots are now also exposed on $scopedSlots as functions. If you work with render functions, it is now recommended to always access slots via $scopedSlots, whether they currently use a scope or not. This will not only make future refactors to add a scope simpler, but also ease your eventual migration to Vue 3, where all slots will be functions.

**Comment by tangbc** [comment]
> @tangbc
> can you review this pr?
> 
> changed $scopedSlots.default to $scopedSlots.item
> and jest passed
> 
> https://vuejs.org/v2/api/#vm-scopedSlots
> 
> > All $slots are now also exposed on $scopedSlots as functions. If you work with render functions, it is now recommended to always access slots via $scopedSlots, whether they currently use a scope or not. This will not only make future refactors to add a scope simpler, but also ease your eventual migration to Vue 3, where all slots will be functions.

OK

**Comment by MoazAlkharfan** [comment]
No thead support?

**Pull request merged**
