### PR TITLE
Add props page-mode Mergeable

### PR DESCRIPTION
**Pull request by Stormtv**
I took #80 and merged it with current version of vue-virtual-scroll-list

### CODE REVIEW

**Comment by Stormtv** [comment]
I tried to get the coverage higher but I'm not an expert with Jest unit testing. I couldn't figure out the proper way to emulate window events.

**Comment by tangbc** [comment]
I seem that demo of `pagemode` still has obvious bugs, such as:
image

This component calculates the rendering area by fixed container height, if using window, it also need 
calculate with window height, it should be trouble.

**Comment by Stormtv** [comment]
Okay I must of missed that I'll take a look again and fix it.

**Comment by tangbc** [comment]
Run `npm run demo:dev` is the develop env of demos in your local.

**Comment by Stormtv** [comment]
I think I fixed the issue you were describing, if I missed something please let me know. I appreciate the feedback!

**Comment by tangbc** [comment]
Thanks, but busy these days, I will check when I'm free.

**Pull request merged**
