### PR TITLE
Dev dynamic remain

### PR DESCRIPTION
**Pull request by dgri**
ADD dynamic on remain and slots changes to avoid scrolling issues when data changes.
Sory for reset the dev mode...

### CODE REVIEW

**Comment by tangbc** [comment]
I' am sorry I have push a few commits before your pr，there is so many change files and conflicts, so can you resolved them at first?

**Comment by tangbc** [comment]
Thank for your contribution, but… your pr has a big change compared to the original.

I think it's better keeping my original demo entry (config), I think every update from others should't remove origin code if it's not wrong.

**Comment by dgri** [comment]
Hello, sorry for that, I had to do this changes really quickly ^^

Thank's for this package you've done ;)

**Comment by tangbc** [comment]
Sorry not free these days, I just checkout the code, I found there is an large file: bigata.json about 42.5M !!😱 I think it's terrible putting such a big test data into repo... 

At last, let me consider the feature "dynamic remain" , I think that could be done by other better ways ...

**Pull request closed without merging**
