### PR TITLE
Add props page-mode

### PR DESCRIPTION
**Pull request by amatakasap**
Could not restore scroll position using scrollBehavior of vue-router.
Therefore, we added pageMode to change the scroll target to "window".

### CODE REVIEW

**Comment by tangbc** [comment]
Can you give a demo or case ? I don't think it's very useful.

**Comment by ConfusedCitizen** [comment]
@amatakasap Thank you for this - this was exactly what I was looking for!

@tangbc The feature makes the scroller for the Virtual Scroller List use the windows scroll-bar instead of the windows scrollbar - so the virtual scrolling is hidden and the standard window scrollbar is used in place.

**Comment by tangbc** [comment]
Is it better to provide a prop `scrollElement` type is selector string or a element to controll scrollBehavior?

**Comment by ConfusedCitizen** [comment]
I'm not sure I totally understand the question - but I think you're referring to the pageMode prop that is part of the changes?
Could you please clarify the question?

**Comment by tangbc** [comment]
@ConfusedCitizen  In this case `remain` and `size` assign what ?

**Comment by ConfusedCitizen** [comment]
@tangbc remain and size remain functionally the same - this change is merely an adjustment to utilise the Window scrollbar instead of a container scrollbar.
If I have some time tomorrow/weekend I'll try to put together a demo of the pageMode.

**Comment by tangbc** [comment]
@ConfusedCitizen It would be better if we could do that. I'm still a little confused about the scene. 😳

**Comment by ConfusedCitizen** [comment]
@tangbc spent an hour putting together a demo on Sunday only to have my PC crash and lose all the work.
I'll try to find some time this week to put together another one :(

**Comment by ConfusedCitizen** [comment]
hey @tangbc, sorry for the long delay - it's been a hectic few months at work.
Here is a very rough sample demo with pageMode enabled.

I have also included the latest version of the plugins index.js with the pageMode changes along with the demo.
Let me know if it's not working for you :) 

Cheers,
ConfusedCitizen

[pagemode-demo.zip](https://github.com/tangbc/vue-virtual-scroll-list/files/3061517/pagemode-demo.zip)

**Comment by tangbc** [comment]
ok, I will check later.

**Comment by Stormtv** [comment]
This PR helped me quite a bit, my UI is using a combination of fixed headers / footers a large center data list (using this lib) and an affixed sidebar that scrolls with the content using https://github.com/eddiemf/vue-affix scroll.

**Comment by tangbc** [comment]
Already pr by #103

**Pull request closed without merging**
